### ISSUE TITLE
an error occurred when using convolve-mtss-rotamers_pre.py

### ISSUE THREAD

**Issue by Gobliu** [MDAnalysis/RotamerConvolveMD#19] opened 2017-09-17 13:51 UTC
Hi all, I am a new user of MDAnalysis. I am trying to use RotamerConvolveMD to explore the possible MTSL conformations and corresponding distances in PRE experiment. Here is the command I used:
~~~~~~~~~~~~~~~~~~~~~~~~~`
convolve-mtss-rotamers_pre.py \
    --resid 696  \
    --clashDistance 2.2  \
    --plotname "dat/peptso-xrd-47.pdf" \
    --outputRawDistances "dat/peptso-xrd" \
    --dcdfilenameAll "dcd/peptso-xrd" \
    --dcdfilenameNoClashes "dcd/peptso-xrd" \
    --useNOelectron \
    frame-4840-0.psf frame-4840-0.pdb
~~~~~~~~~~~~~~~~~~~~~~~~~
However, an error occurred which I cannot fix:
~~~~~~~~~~~~~~~~~~~~~~~~~
2017-09-15 16:46:48,425 MDAnalysis.core.universe DEBUG    Universe.load_new(): loading frame-4840-0.pdb...
2017-09-15 16:46:48,446 MDAnalysis.app CRITICAL protein structure and/or trajectory not correctly specified
~~~~~~~~~~~~~~~~~~~~~~~~~
Could you please help me to take a look? All the related files are provided.
[PRE.zip](https://github.com/MDAnalysis/RotamerConvolveMD/files/1309112/PRE.zip)

**Comment by lukas-stelzl** [comment] 2017-09-17 14:17
Hi @Gobliu,
Awesome that you're trying out RotamerConvolveMD :-) and thanks for opening the issue. I'll look at files you uploaded on Monday, if that's ok.

**Comment by orbeckst** [comment] 2017-09-17 15:13
Can you try loading your PSF and PDB separately, just using MDAnalysis (which you have already installed)? Start the `python` interpreter
```
python
```
and in the interpreter type the following lines and hit return after each line: Specifically, what is the output of 
```python
import MDAnalysis as mda
mda.start_logging()

print(mda.__version__)

utop = mda.Universe("frame-4840-0.psf")
print(utop)

updb = mda.Universe("frame-4840-0.pdb")
print(updb)

u = mda.Universe("frame-4840-0.psf", "frame-4840-0.pdb")
print(u)
```

(Also copy and paste the content of the log file.)

**Comment by Gobliu** [comment] 2017-09-18 10:01
Hi all.
I think I found one problem. The PSF file and PDB file have different atom numbers.
~~~~~~
>>>print(utop)
<Universe with 4659 atoms>
>>>print(updb)
<Universe with 4942 atoms>
>>>u = mda.Universe("frame-4840-0.psf", "frame-4840-0.pdb")
...
IndexError: index 4659 is out of bounds for axis 0 with size 4659
~~~~~~
If I am not wrong, the PSF file is required only for a trajectory but not for a structure. So I tried the following command:
~~~~~~
convolve-mtss-rotamers_pre.py \
    --resid 696  \
    --clashDistance 2.2  \
    --plotname "dat/peptso-xrd-47.pdf" \
    --outputRawDistances "dat/peptso-xrd" \
    --dcdfilenameAll "dcd/peptso-xrd" \
    --dcdfilenameNoClashes "dcd/peptso-xrd" \
    --useNOelectron \
    frame-4840-0.pdb
~~~~~~
But there is another error:
~~~~~~
2017-09-18 17:49:40,737 MDAnalysis.core.universe DEBUG    _process_attr: Adding <MDAnalysis.core.topologyattrs.Bonds object at 0x7f5ea2455110> to topology
2017-09-18 17:49:40,737 MDAnalysis.core.universe DEBUG    Universe.load_new(): loading dcd/peptso-xrd-696-all.dcd...
2017-09-18 17:49:40,815 MDAnalysis.app CRITICAL no distances found between the spin pair!
~~~~~~
Could you please help me to solve this?

**Comment by lukas-stelzl** [comment] 2017-09-18 12:14
I can reproduce your error message with the inputs you have provided. 

Once the script fitted the MTSSL structures, it looks for distances to amide protons. 

` proteinHN = proteinStructure.select_atoms("protein and name HN") `

Line 112 in convolve_pre.py and then in line 126 it loops over the amide protons.

Looking at your structure with VMD, I don't find any atoms with that name. The amide proteins are just called "H". 

You could try to use a PSF file with the same atom numbering as the PDB file. I'd hope that the PSF file might fix the atom name problem.

**Comment by Gobliu** [comment] 2017-09-21 10:15
Thanks a lot. Recently I am busy with some experimental stuff. I'll try this as soon as possible.

**Comment by Gobliu** [comment] 2017-10-05 10:44
Hi @lukas-stelzl,
I renamed all the amide proton from "H" to "HN", and then the script works fine. Thanks.
But I have two more questions.
1. I need to use RotamerConvolveMD to go through millions of pdb files. All I need is the *.dat file which contains all the distance information. Can I disable the generation of other output files to accelerate the process, especially the *.pdf file?
2. When I changed the clashDistance value from default value 2.2 to a value larger than 2.5, an error occurs. Do you know why?
~~~~~
RuntimeError: no distances from between the spin pair!
~~~~~
Here are the files I am using.
[distance.zip](https://github.com/MDAnalysis/RotamerConvolveMD/files/1358973/distance.zip)

**Comment by lukas-stelzl** [comment] 2017-10-05 13:47
I'm glad that the script works now :) 

@katrinr, do you have an idea of how to disable the generation of output files to speed up the calculation ? 

It is possible that by increasing the clashDistance no spin labels fit the structure, as they is just not enough space for the spin label to be mapped to your protein.

**Comment by orbeckst** [comment] 2017-10-05 16:56
> I need to use RotamerConvolveMD to go through millions of pdb files

Are these "millions of PDB files" different conformations of the same protein or different proteins. If it is the latter then yes, you have to things individually. If  you are looking at an ensemble then do you really need the information for each individual structure or is knowing the distributions enough? If it is the latter case, then it would be more efficient to combine your PDB files into a trajectory.

**Comment by orbeckst** [comment] 2017-10-05 18:50
I added the `--no-plot` option to the scripts. They also work now with the latest MDAnalysis releae.

**Comment by katrinr** [comment] 2017-10-06 15:02
Thanks, @orbeckst!

@Gobliu, I am also working with tons of single pdbs and at the end I scripted everything by calling RotamerConvolveMD individually for each pdb. Cool, that you are using RotamerConvolveMD! :)

**Comment by lukas-stelzl** [comment] 2017-10-10 09:12
Hi @Gobliu, 
Does everything work for you or do you need further help?  

I just talked to @katrinr  and @Gobliu's initial problem can be fixed in general. 
@katrinr  suggests to change the atom selection for the PRE calculation:

`proteinHN = proteinStructure.select_atoms("protein and name HN") `

to

`proteinHN = proteinStructure.select_atoms("protein and (name HN or name H)") `

as amide protons are called H in the PDB. I checked at http://www.bmrb.wisc.edu/ref_info/atom_nom.tbl and there does not seem a downside to extending the selection.

**Comment by orbeckst** [comment] 2017-10-11 05:51
@Gobliu do you have any more comments/questions? Otherwise @lukas-stelzl or someone else will close this issue in the next few days.

**Comment by Gobliu** [comment] 2017-10-11 06:23
Hi @orbeckst and @lukas-stelzl, I am still trying to make the --no-plot option work. I updated RotamerConvolveMD by pip. 
~~~~~
pip install --upgrade RotamerConvolveMD
~~~~~
But I can not see the --no-plot flag when using --help command. It seems the update is not successful. One more thing, do I need to remove "--plotname "dat/peptso-xrd-47.pdf" when I add --no-plot?

By the way, I really need the distance information for each individual structure. I'll use that to generate individual PRE data for everyone in the structure pool, then select an optimal ensemble from the pool.

**Comment by orbeckst** [comment] 2017-10-11 08:54
At the moment you're still installing the latest release because you're missing a slash `/` at the end:
```
pip install --upgrade RotamerConvolveMD/
```

or just do
```
cd RotamerConvolveMD
pip install --upgrade .
```

**Comment by orbeckst** [comment] 2017-10-11 08:59
Btw, there are a bunch of other files being written out. Which ones do you actually need for your purpose? (I am asking because we should make writing them optional as it can slow down things when one runs on single files. In the meantime, you could hack your source code and comment out the writes that you don't need...)

**Comment by Gobliu** [comment] 2017-10-11 10:41
I've reinstalled RotamerConvolveMD and everything looks fine now. Thanks a lot.
All I need is the DAT file which generated by this command:
~~~~
  --outputRawDistances "dat/peptso-xrd" \
~~~~
I'll try to comment out other outputs. :)

**Comment by orbeckst** [comment] 2017-10-11 16:45
Glad that things are working. 

Can you let us know by how much processing is sped up when you comment out "unnecessary" output?

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by Gobliu** [comment] 2017-10-16 03:15
Sure. But I will be on leave for few weeks, and cannot finish everything before that.
Maybe we can close this issue. I can update to you by email once I got the result.

**Comment by orbeckst** [comment] 2017-10-17 07:21
Thanks.

We can close the issue but just keep commenting on it when you have results to share. That's easier than email and more useful for the developers because there's a record near the code and not just in someone's inbox. And everyone on the issue will get notified by email.

**Closed as completed by orbeckst** 2017-10-17 07:21 UTC
